name: build
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [15, 11]
      fail-fast: true
    steps:
      - uses: actions/checkout@v2
      - name: JDK ${{ matrix.java }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      - name: Cache Gradle packages
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-${{ matrix.java }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-${{ matrix.java }}-gradle
      - name: Build
        run: ./gradlew build test
      - name: CodeCov
        uses: codecov/codecov-action@v1
        with:
          directory: build/reports/jacoco/
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ban-jdk-${{ matrix.java }}
          path: '**/build/libs/*.jar'
